#!/usr/bin/env ruby

require 'json'
require 'optparse'
require 'pathname'

$: << File.expand_path('../../lib', Pathname.new(__FILE__).realpath)

require 'junoser'


command = nil
opts = OptionParser.new do |opts|
  opts.banner = 'junoser: an juniper configuration parser'
  opts.define_head 'Usage: junoser [options] [path]'
  opts.separator ''
  opts.separator 'Options:'

  opts.on '-c', '--check', 'Verify syntax' do
    command = :check
  end

  opts.on '-C', '--check-lines', 'Verify syntax and display invalid line numbers in JSON format' do
    command = :check_lines
  end

  opts.on '-d', '--display-set', 'Translate to "display set" form' do
    command = :display_set
  end

  opts.on '-s', '--structured', 'Translate to structured form' do
    command = :struct
  end

  opts.on_tail '-h', '--help', 'Show this message' do
    puts opts
    exit
  end

  opts.on_tail '-v', '--version', 'Show version' do
    puts Junoser::VERSION
    exit
  end
end
opts.parse!

case command
when :check
  abort unless Junoser::Cli.commit_check($<)
when :check_lines
  puts JSON.dump(Junoser::Cli.commit_check_lines($<))
when :display_set
  puts Junoser::Cli.display_set($<)
when :struct
  puts Junoser::Cli.struct($<)
else
  puts opts
  abort
end
